spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/hotel_reservation}
    username: ${DB_USERNAME:hotel_user}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: user_svc
    
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}

logging:
  level:
    com.hotel.user: INFO
    org.springframework.security: WARN
    root: WARN