spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/hotel_reservation}
    username: ${DB_USERNAME:hotel_user}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: hotel_svc
    
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

logging:
  level:
    com.hotel.hotel: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN
