spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hotel_reservation
    username: hotel_user
    password: hotel_password
  jpa:
    properties:
      hibernate:
        default_schema: hotel_svc
    
  redis:
    host: redis
    port: 6379

logging:
  level:
    com.hotel.hotel: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN